### ISSUE TITLE
Remove Chat functionality

### ISSUE THREAD

**Issue by bduff9** [bduff9/nfl-meteor#112]
Remove and delete all chat functionality.  Replace link in sidebar with external link to https://join.slack.com/t/asitewithnoname/shared_invite/enQtNDIyNzUxNTAxMzk0LTIxNmFjOWVkMDk2N2Q2ZDNmMjIxMjQ1NzgwMzUzZTFhMmU3OWIyZmVmZmQ1ZDViZmU5YTJhNmQwYjIxMjYwY2E

On click, show alert that they are leaving the pool.  If cancel, do nothing.  If OK, open new tab with link above as URL.

**Comment by bduff9** [comment]
Once done, @balexander82 to approve/edit the text on sidebar and in alert.

**Comment by bduff9** [comment]
Testing Slack functionality is back

**Comment by balexander82** [comment]
Text in sidebar and alert is fine by me.
