### ISSUE TITLE
Improve Payments Process

### ISSUE THREAD

**Issue by bduff9** [bduff9/nfl-meteor#136]
Couple of actual issues plus some enhancements we've talked about here:

Issue: View Payments screen shows that people owe less than the entry if they've won prior to paying
- [ ] We've also talked about moving my spreadsheet into the app as a new screen
- [x] Store prize amounts in DB
- [ ] Change View Payments to show that people owe the full amount until the prizes have been set
- [ ] Alter View Payments screen to allow people to see different payment methods on the fly (default to their payment method but let them also see others with a button/dropdown)

**Comment by balexander82** [comment]
Add logic for different scenarios of survivor pool split payouts:

1. 1 first place and 1 second place
2. 1 first place and tied second place
3. Tied first place and no second place

**Comment by bduff9** [comment]
Moved to Linear
