### ISSUE TITLE
Make Emails Pretty(er)

### ISSUE THREAD

**Issue by bduff9** [bduff9/nfl-meteor#44]
Instead of plain text, set up all emails to use HTML.
- [x] Email verification
- [x] Welcome new user
- [x] Welcome back returning user
- [x] Reminder to submit picks
- [x] Quick pick
- [x] Confirmation of submitting picks
- [x] Confirmation when all users submit picks
- [x] Reset password email
- [x] Generic email template

**Comment by balexander82** [comment]
Research meteor emails

**Comment by bduff9** [comment]
Working
