### ISSUE TITLE
Print view of View All Picks screen needs work

### ISSUE THREAD

**Issue by balexander82** [bduff9/nfl-meteor#52]
The print picks page cuts off after 13 games. Can we shrink this to fit on the page when printing?

**Comment by bduff9** [comment]
The issue we saw was with print view of view all picks cutting off the first table too early.  @balexander82 to look at this issue across browsers as it should be a CSS change

**Comment by bduff9** [comment]
Unsure if this is something people actually want in 2020.  @balexander82 Can you please do a little digging and see if this is worth looking at for 2021?

**Comment by bduff9** [comment]
Let's remove the print button since no one uses it

**Comment by bduff9** [comment]
Will not recreate print button on this screen in new pool
