### ISSUE TITLE
Indicate user sign up method on admin screen

### ISSUE THREAD

**Issue by balexander82** [bduff9/nfl-meteor#54]
I don't remember if we handled it by the end of last season, but when people forgot their credentials and we reset their password, if they signed up with facebook this wouldn't work and we would have to assume they signed up with facebook. Is there somewhere we can indicate how they signed up to help people know.

**Comment by bduff9** [comment]
- [ ] Add column(s) to indicate what auth methods a user has
- [ ] Add forgot password link to sign in page
- [ ] Look into adding captcha to both register and forgot password screens

**Comment by bduff9** [comment]
Closing for now, if we get bots we can add captcha but afaik, we have 0 issue with bots thus far.
