### ISSUE TITLE
Add More Help on Screens

### ISSUE THREAD

**Issue by bduff9** [bduff9/nfl-meteor#61]
Let's research our options here to see what would work best.  Also, should we have a tour for the entire pool or a per page tour?  Both?

**Comment by bduff9** [comment]
Let's look at this more in the scope of how we can add some help to screens to make it easier for people to find things.  For whatever reason, it seems like there aren't many questions on how to do things or where things are this year, so this is low priority.

**Comment by bduff9** [comment]
@balexander82 Do you have any more thoughts on this?  I think adding help is good so the barrier to entry for new people is as low as possible, but would like to get a better feeling for what will help so we can plan scope/level of effort

**Comment by balexander82** [comment]
I think having a tour for main features would be good:

1. Edit Profile (Choose auto picks, notifications and payment method)
2. View Payments (See what they owe and how to pay)
3. Dashboard (point out weekly and overall views)
4. Make picks (drag and drop points, team help hover, tiebreaker explanation)
4. View all picks (point out what if)
5. Survivor (only if playing survivor)

**Comment by bduff9** [comment]
Moved to Linear
