### ISSUE TITLE
Email images and styling

### ISSUE THREAD

**Issue by balexander82** [bduff9/nfl-meteor#85]
Emails are missing images and possibly some styling.

**Comment by balexander82** [comment]
Not running this from a public IP, so styling and images will not load. Stop asking this question!

**Comment by bduff9** [comment]
Sounds like your environment variable (ROOT_URL) is blank based on this and the broken links. 
 Try setting the ROOT_URL to http://localhost:3000/ using something like the following:
https://stackoverflow.com/questions/19715617/set-root-url-of-meteor-app-on-windows

**Comment by balexander82** [comment]
Potentially related to AOL mail. Gmail allows links to function in the email, however images and styling still do not render.

**Comment by bduff9** [comment]
I think you needed ROOT_URL and not AOL for your links, the images are only available on a public IP.  If the live server has this issue, we'll look into it or for next year, we can set you up with a public IP for testing.  Closing for now.
